modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="peat_mod"
version="1.0.01.20.1"
displayName="Peat Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Absolute Narwhal"
description="Adds Peat to Minecraft"

[[dependencies.peat_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




